// Generated by gencpp from file rhino_ros/command.msg
// DO NOT EDIT!


#ifndef RHINO_ROS_MESSAGE_COMMAND_H
#define RHINO_ROS_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rhino_ros
{
template <class ContainerAllocator>
struct command_
{
  typedef command_<ContainerAllocator> Type;

  command_()
    : destination()
    , grip(0)
    , softhome(0)  {
      destination.assign(0);
  }
  command_(const ContainerAllocator& _alloc)
    : destination()
    , grip(0)
    , softhome(0)  {
      destination.assign(0);
  }



   typedef boost::array<int32_t, 5>  _destination_type;
  _destination_type destination;

   typedef int32_t _grip_type;
  _grip_type grip;

   typedef int32_t _softhome_type;
  _softhome_type softhome;




  typedef boost::shared_ptr< ::rhino_ros::command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rhino_ros::command_<ContainerAllocator> const> ConstPtr;

}; // struct command_

typedef ::rhino_ros::command_<std::allocator<void> > command;

typedef boost::shared_ptr< ::rhino_ros::command > commandPtr;
typedef boost::shared_ptr< ::rhino_ros::command const> commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rhino_ros::command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rhino_ros::command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rhino_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rhino_ros': ['/home/youbot/catkin_ws/src/rhino_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rhino_ros::command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rhino_ros::command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rhino_ros::command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rhino_ros::command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rhino_ros::command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rhino_ros::command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rhino_ros::command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16d9779b648110c827c3280a76afbcab";
  }

  static const char* value(const ::rhino_ros::command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16d9779b648110c8ULL;
  static const uint64_t static_value2 = 0x27c3280a76afbcabULL;
};

template<class ContainerAllocator>
struct DataType< ::rhino_ros::command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rhino_ros/command";
  }

  static const char* value(const ::rhino_ros::command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rhino_ros::command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[5] destination\n\
int32 grip\n\
int32 softhome\n\
";
  }

  static const char* value(const ::rhino_ros::command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rhino_ros::command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.destination);
      stream.next(m.grip);
      stream.next(m.softhome);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rhino_ros::command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rhino_ros::command_<ContainerAllocator>& v)
  {
    s << indent << "destination[]" << std::endl;
    for (size_t i = 0; i < v.destination.size(); ++i)
    {
      s << indent << "  destination[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.destination[i]);
    }
    s << indent << "grip: ";
    Printer<int32_t>::stream(s, indent + "  ", v.grip);
    s << indent << "softhome: ";
    Printer<int32_t>::stream(s, indent + "  ", v.softhome);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RHINO_ROS_MESSAGE_COMMAND_H
