// Generated by gencpp from file rhino_ros/positionRequest.msg
// DO NOT EDIT!


#ifndef RHINO_ROS_MESSAGE_POSITIONREQUEST_H
#define RHINO_ROS_MESSAGE_POSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rhino_ros
{
template <class ContainerAllocator>
struct positionRequest_
{
  typedef positionRequest_<ContainerAllocator> Type;

  positionRequest_()
    : request(0)  {
    }
  positionRequest_(const ContainerAllocator& _alloc)
    : request(0)  {
    }



   typedef uint8_t _request_type;
  _request_type request;




  typedef boost::shared_ptr< ::rhino_ros::positionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rhino_ros::positionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct positionRequest_

typedef ::rhino_ros::positionRequest_<std::allocator<void> > positionRequest;

typedef boost::shared_ptr< ::rhino_ros::positionRequest > positionRequestPtr;
typedef boost::shared_ptr< ::rhino_ros::positionRequest const> positionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rhino_ros::positionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rhino_ros::positionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rhino_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rhino_ros': ['/home/youbot/catkin_ws/src/rhino_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rhino_ros::positionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rhino_ros::positionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rhino_ros::positionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rhino_ros::positionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rhino_ros::positionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rhino_ros::positionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rhino_ros::positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "089baa2277657b640486f0a51e062aba";
  }

  static const char* value(const ::rhino_ros::positionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x089baa2277657b64ULL;
  static const uint64_t static_value2 = 0x0486f0a51e062abaULL;
};

template<class ContainerAllocator>
struct DataType< ::rhino_ros::positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rhino_ros/positionRequest";
  }

  static const char* value(const ::rhino_ros::positionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rhino_ros::positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 request\n\
";
  }

  static const char* value(const ::rhino_ros::positionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rhino_ros::positionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct positionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rhino_ros::positionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rhino_ros::positionRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RHINO_ROS_MESSAGE_POSITIONREQUEST_H
